
networks:
  diamond-frontend-network:

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    networks:
      - diamond-frontend-network
    labels:
      - "traefik.enable=true"
      # change Host to diamond.ncsa.illinois.edu in Prod and diamond.localhost in Local
      - "traefik.http.routers.api.rule=Host(`diamond.ncsa.illinois.edu`) && PathPrefix(`/api`) "
      - "traefik.http.services.api.loadbalancer.server.port=5328"

  client:
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    networks:
      - diamond-frontend-network
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      # change Host to diamond.ncsa.illinois.edu in Prod and diamond.localhost in Local
      - "traefik.http.routers.client.rule=Host(`diamond.ncsa.illinois.edu`) && PathPrefix(`/`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.1
    command:
      - --log.level=DEBUG
      - --api
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # Activate tls entrypoint resolver
      - --entrypoints.https.http.tls.certresolver=myresolver
      # letsencrypt
      - --certificatesresolvers.myresolver.acme.email=diamond-project@lists.ncsa.illinois.edu
      - --certificatesresolvers.myresolver.acme.storage=/certs/acme.json
      # uncomment to use testing certs
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      # Enabling docker providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT:-8000}:80"
      - "${TRAEFIK_HTTPS_PORT:-8443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker daemon socket
      - ./certs:/certs # Mount the certificates directory for acme.json file
    networks:
      - diamond-frontend-network
    labels:
      - "traefik.enable=true"
      # change Host to traefik.diamond.ncsa.illinois.edu in Prod and traefik.localhost in Local
      - "traefik.http.routers.traefik.rule=Host(`traefik.diamond.ncsa.illinois.edu`)"  # Dashboard
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

