name: diamond-frontend

networks:
  diamond-frontend-network:

  # proxy:
  #   external: true
  #   name: proxy
  # default:
  #   name: diamond-frontend-network
  #   driver: bridge

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    networks:
      - diamond-frontend-network
    ports:
      - 5328:5328
    labels:
      - "traefik.http.routers.api.rule=Host(`${HOST}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=5328"
  
  client:
    build:
      context: .
      # target: runner
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    #   - /app/node_modules/
    #   - /app/.next/
    networks:
      - diamond-frontend-network
    ports:
      - 3000:3000
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.routers.client.rule=Host(`${HOST}`)"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.1
    command:
      - --log.level=DEBUG
      - --api
      - --api.dashboard=true
      - --api.insecure=true
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.web.address=:3000
      - --entrypoints.websecure.address=:3001
      # Enabling docker providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT-8000}:80"
      - "${TRAEFIK_HTTPS_PORT-8443}:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker daemon socket
    networks:
      - diamond-frontend-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"  # Dashboard
      - "traefik.http.routers.traefik.entrypoints=http,https,web,websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.middlewares=traefik-ipallowlist"
      - "traefik.http.middlewares.traefik-ipallowlist.ipallowlist.sourcerange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`0.0.0.0`)"
      # - "traefik.docker.network=diamond-frontend-network"
      
  