providers = ["...", "python"]

[phases.setup]
nixPkgs = ["...", "nodejs_22", "python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  # Install Python requirements using python -m pip
  "python -m pip install -r api/requirements.txt",
  # Install Node dependencies
  "npm install -g pnpm",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[start]
cmd = "sh ./start.sh"

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
HOSTNAME = "0.0.0.0"
PYTHONPATH = "/opt/venv/lib/python3.12/site-packages:${PYTHONPATH}"
NIXPACKS_PYTHON_VERSION = "3.12"

[[processes]]
name = "next"
command = "node .next/standalone/server.js"
port = 3000

[[processes]]
name = "flask"
command = "gunicorn --workers=1 --threads=100 --worker-class=gthread api.backend.index:app --bind=0.0.0.0:5328"
port = 5328 