providers = ["...","python"]

[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = [
  "npm install -g pnpm"
]

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
HOSTNAME = "0.0.0.0"
PYTHONPATH = "/app"
PATH = "/root/.npm-global/bin:${PATH}"

[phases.install]
cmds = [
  # Install Python requirements using python -m pip
  # Install Node dependencies
  "export PATH=\"/root/.npm-global/bin:$PATH\"",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]


[[processes]]
name = "next"
command = "node .next/standalone/server.js"
port = 3000

[[processes]]
name = "flask"
command = "gunicorn --workers=1 --threads=100 --worker-class=gthread api.backend.index:app --bind=0.0.0.0:5328"
port = 5328 