[phases.setup]
aptPkgs = [
  "python3-venv"
]

nixPkgs = [
  "nodejs_22",
  "python312",
  "python312Packages.pip",
  "python312Packages.flask",
  "python312Packages.flask-cors",
  "python312Packages.flask-sqlalchemy",
  "python312Packages.gunicorn",
  "python312Packages.setuptools",
  "python312Packages.requests",
  "python312Packages.python-dotenv",
  "python312Packages.virtualenv"
]

[phases.install]
cmds = [
  # Create and activate virtual environment
  "python -m venv .venv",
  "source .venv/bin/activate",
  # Install Python requirements in venv
  "pip install -r api/requirements.txt",
  # Install Node dependencies
  "npm install -g pnpm",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[start]
cmd = "sh ./start.sh"

[variables]
NODE_ENV = "production"
FLASK_ENV = "production"
HOSTNAME = "0.0.0.0"
VIRTUAL_ENV = "/app/.venv"
PATH = "/app/.venv/bin:${PATH}"

[[processes]]
name = "next"
command = "node .next/standalone/server.js"
port = 3000

[[processes]]
name = "flask"
command = "source .venv/bin/activate && gunicorn --workers=1 --threads=100 --worker-class=gthread api.backend.index:app --bind=0.0.0.0:5328"
port = 5328 