CREATE TABLE "dataset" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dataset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"collection_uuid" varchar NOT NULL,
	"dataset_path" varchar NOT NULL,
	"public" boolean DEFAULT false NOT NULL,
	"machine_name" varchar NOT NULL,
	"dataset_metadata" text,
	"identity_id" varchar NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dataset" ADD CONSTRAINT "dataset_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "public"."profile"("identity_id") ON DELETE no action ON UPDATE no action;